% ---------------------------------------------------------------------------------------------
% 
% MCI LaTeX Documentation Re-Caffeinated !! -DTMc
% -----------------------------------------------
% 
% INTRODUCTION
% ------------
% 
% This is a LaTeX document formatting designed to cater to all possible student requirements
% regarding:
% - document preparation,
% - presentation,
% - poster,
% - and thesis writing.
% All the aforementioned documents are bundled up as a class called mcidoc.
% 
% PURPOSE
% -------
% The main ethos of this class is to standardise and streamline document creation which abides
% to the standards set by the institution with regards to:
% - the font-size,
% - page spacing,
% - line spacing,
% - caption style,
% - languages specific settings
% - header/footer styles
% and so on so forth.
% 
% A second goal it to create a repository to house a standard class to minimise any friction
% between your work and the presentation. Therefore care was given to how the class behaves
% to minimise the dependencies it needs and give you key/value pairs to modify the document
% as you see fit.
% 
% 
% NOTE: This class has been tested on different computers, different OSs and LuaTeX
% : and pdfTeX. However, as with everything, there will always be edge cases and I am sure
% : to that end, if you let me know anonymously or just let me know via email, I can 
% : squash the bugs or add any feature it may seem necessary.
% 
% 
% WARNING: While I will try to help with any problem this class might have, it is by no means
% : I am providing any kind of WARRANTY or TECHNICAL SUPPORT. There will be
% : documentation and some example documents which should compile without any
% : additional configuration. Nevertheless, I can only help with the errors from code
% : and not with your personal LaTeX development environment (i.e., TeXStudio).
% 
% -DTMc
% 
% CLASS HEADER --------------------------------------------------------------------------------
%
