
#+TITLE: LaTeX Class for MCI (mcidoc)


MCI LaTeX Template Re-Caffeinated!!

version: 1.00

Greetings!!!


This is a LaTeX document formatting designed to cater to all possible student requirements
Regarding document preparation, presentation, poster and thesis writing. All bundled up in
on class called mcidoc. Aside from trying to standardise formatting across different report
style, the goal here is also to have a place to have an UNOFFICIAL/OFFICIAL repo housing all
the necessary formatted text.

 *NOTE:* This class has been tested on different computers, different OSs and LuaTeX
       and pdfTeX. However, as with everything, there will always be edge cases and I am sure
       to that end, if you let me know anonymously or just let me know via email, I can 
       squash the bugs or add any feature it may seem necessary.


 WARNING: While I will try to help with any problem this class might have, it is by no means
          I am providing any kind of WARRANTY or TECHNICAL SUPPORT. There will be
          documentation and some example documents which should compile without any
          additional configuration. Nevertheless, I can only help with the errors from code
          and not with your personal LaTeX development environment (i.e., TeXStudio). 
