# Created 2026-07-01 Wed 11:18
#+title: mcidoc Student Documentation
#+author: Daniel McGuiness
#+filetags: :manual:code:
** Table of Contents                                                  :TOC_5:
- [[#introduction][Introduction]]
  - [[#an-overview-of-mcidoc][An Overview of mciDoc]]
    - [[#purpose-of-making][Purpose of Making]]
* Introduction

This repo contains ~mcidoc~, a LaTeX class for producing guideline compliant
documentation for M.Sc and B.Sc students.

This is version 2026.SS.1, last updated on 01.07.2026, of The mcidoc Manual,
for use with lualatex.

Copyright 2026, -DTMc

The manual for ~mcidoc~ can be accessed [[https://dtmc0945.github.io/C-MCI-LaTeX-Class-mcidoc/][here]].

#+begin_quote
This program may be distributed and/or modified under the conditions of the
LaTeX Project Public License, either version 1.1 of this license or (at your
option) any later version. The latest version of this license is in
http://www.latex-project.org/lppl.txt and version 1.1 or later is part of all
distributions of LaTeX version 1999/06/01 or later.

This program is distributed in the hope that it will be useful, but WITHOUT ANY
WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A
PARTICULAR PURPOSE.
#+end_quote
** An Overview of mciDoc

~mcidoc~ is a LaTeX document class designed to provide students studying at *MCI
Mechatonics* with all their documentation needs, whether it is to write a simple
report or to write a their graduation thesis whether it is a single or a double
degree.

As it stands the following document types are supported and are implemented
for both *english* and *german.*

- Thesis
- Report
- Paper (WIP)
- Notes (WIP)
- Slide (WIP)
- Poster (WIP)

All these aforementioned sub-classess will be explained in the following
sections.
*** Purpose of Making

There are three (3) reasons for the creation of this class.

The first, is to standardise and streamline document creation which abides to
the standards set by the MCI with regards to:

- Font-size, figure captions, bibliography, ...
- Margin spacing, header and footer spacing, text information, ...
- Spacing between lines, linebreak settings, spacing of headers, ...
- Language determined grammatical rules (when to hypenate and caption text and
  proper quoatation marks)
- Simple error-correction codes to minimise wrong entering of values,

and so on so forth.

Its second purpose is to create a repository to house a *standardised* class to
minimise any friction between the work of the student and the representation of
the content.

#+begin_quote
Care was given to how the class behaves to minimise its interaction with other
packages the end-user might need for their work. The class only patches certain
commands but never redefines them.
#+end_quote

As a sidenote, ~mcidoc~ was also designed with customisation in mind by
configuring its settings through the options presented in the ~\documentclass~ and
using the macro ~\SetMCI{}~ which all its features are explained in this
documentation.

The last purpose is perhaps more in line of streamlining. While LaTeX is an
excellent typesetting language with is very powerful capabilities, it is
nevertheless a language with its quirks and customs that may not prove to be
very useful outside of its own domain and therefore the user should not be
worried of these quirks.

The user should only be responsible of the content they create. The form of the
documentation, and how the content is presented is taken care of the class
designer.
