
#+TITLE: LaTeX Class for MCI (mcidoc)


** Table of Contents :TOC_5:
  - [[#introduction][Introduction]]
  - [[#the-class][The Class]]
    - [[#documentclass][Documentclass]]
      - [[#state][State]]
  - [[#faq][FAQ]]

** Introduction

MCI LaTeX Template Re-Caffeinated!!

version: 1.00

Greetings!!!


This is a LaTeX document formatting designed to cater to all possible student requirements
Regarding document preparation, presentation, poster and thesis writing. All bundled up in
on class called mcidoc. Aside from trying to standardise formatting across different report
style, the goal here is also to have a place to have an UNOFFICIAL/OFFICIAL repo housing all
the necessary formatted text.

 *NOTE:* This class has been tested on different computers, different OSs and LuaTeX
       and pdfTeX. However, as with everything, there will always be edge cases and I am sure
       to that end, if you let me know anonymously or just let me know via email, I can 
       squash the bugs or add any feature it may seem necessary.


 WARNING: While I will try to help with any problem this class might have, it is by no means
          I am providing any kind of WARRANTY or TECHNICAL SUPPORT. There will be
          documentation and some example documents which should compile without any
          additional configuration. Nevertheless, I can only help with the errors from code
          and not with your personal LaTeX development environment (i.e., TeXStudio). 


** The Class

*** Documentclass

Below is an example execution of the class ~mcidoc~

#+begin_src latex
\documentclass[   
state       = Report,                       % (Report | Slide | Thesis | Poster)
lang        = EN,                           % (DE     | EN) 
degree      = BSc,                          % (BSc    | MSc)
code-engine = listings,                     % (minted | listings | none)
title-page  = nouveau,                      % (tudor  | nouveau)
dept        = MECH                          % (MECH   | SBT)
]{mcidoc} 
#+end_src

As you can see the class have a wide variety of options which all are shown in the commented
lines (%).

Let's go through each of them

**** State

This is the variable which controls HOW the document looks and feels from a practical
perspective, as in each document abides certain forms, shapes and standards and the ~state~
variable is what controls it.

The options are as follows:

| KEY    | DESCRIPTION                                                                                                                                                                   |
|--------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| Report | The standard report class which is meant to be used in any lecture assignment. The document is based on scrreprt and does simple customisation on it to conform to standards. |
| Slide  | Generates a slide with MCI logos and design language. Uses beamer as base                                                                                                     |
| Thesis | Thesis structure based on scrbook and conforms to past thesis structures.                                                                                                     |
| Poster | Generates a Poster in A3 format using MCI style (WIP)                                                                                                                         |

** FAQ




-DTMc
