# Created 2026-07-01 Wed 12:42
#+title: mcidoc Student Documentation
#+author: Daniel McGuiness
#+filetags: :manual:code:

** Table of Contents                                                  :TOC_5:
- [[#introduction][Introduction]]
  - [[#an-overview-of-mcidoc][An Overview of mciDoc]]
    - [[#purpose-of-making][Purpose of Making]]
  - [[#frequently-asked-questions][Frequently Asked Questions]]
      - [[#where-can-i-download-the-documentclass][Where can I download the documentclass?]]
      - [[#what-is-setmci--how-do-i-use-it][What is SetMCI ? How do I use it?]]
      - [[#what-is-latex-isnt-is-a-type-of-plastic][What is LaTeX? Isn't is a type of plastic?]]
      - [[#i-dont-know-what-to-do-with-this-file-what-is-a-cls-file-][I Don't know what to do with this file. What is a .cls file ?]]
      - [[#i-want-to-use-word-docx-instead-of-latex-will-you-help-me][I want to use word (.docx) instead of LaTeX. Will you help me?]]
      - [[#can-i-use-it-in-overleaf][Can I use it in Overleaf?]]
      - [[#what-editor-should-i-use][What Editor Should I Use?]]
      - [[#ive-found-a-bug-how-can-i-report-it][I've found a Bug. How can I Report It?]]
  - [[#patch-information][Patch Information]]
    - [[#release-ss20262][Release SS.2026.2]]

* Introduction

This repo contains ~mcidoc~, a LaTeX class for producing guideline compliant
documentation for M.Sc and B.Sc students.

This is version 2026.SS.1, last updated on 01.07.2026, of The mcidoc Manual,
for use with lualatex.

Copyright 2026, -DTMc

The manual for ~mcidoc~ can be accessed [[https://dtmc0945.github.io/C-MCI-LaTeX-Class-mcidoc/][here]].

#+begin_quote
This program may be distributed and/or modified under the conditions of the
LaTeX Project Public License, either version 1.1 of this license or (at your
option) any later version. The latest version of this license is in
http://www.latex-project.org/lppl.txt and version 1.1 or later is part of all
distributions of LaTeX version 1999/06/01 or later.

This program is distributed in the hope that it will be useful, but WITHOUT ANY
WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A
PARTICULAR PURPOSE.
#+end_quote

** An Overview of mciDoc

~mcidoc~ is a LaTeX document class designed to provide students studying at *MCI
Mechatonics* with all their documentation needs, whether it is to write a simple
report or to write a their graduation thesis whether it is a single or a double
degree.

As it stands the following document types are supported and are implemented
for both *english* and *german.*

- Thesis
- Report
- Paper (WIP)
- Notes (WIP)
- Slide (WIP)
- Poster (WIP)

All these aforementioned sub-classess will be explained in the following
sections.

*** Purpose of Making

There are three (3) reasons for the creation of this class.

The first, is to standardise and streamline document creation which abides to
the standards set by the MCI with regards to:

- Font-size, figure captions, bibliography, ...
- Margin spacing, header and footer spacing, text information, ...
- Spacing between lines, linebreak settings, spacing of headers, ...
- Language determined grammatical rules (when to hypenate and caption text and
  proper quoatation marks)
- Simple error-correction codes to minimise wrong entering of values,

and so on so forth.

Its second purpose is to create a repository to house a *standardised* class to
minimise any friction between the work of the student and the representation of
the content.

#+begin_quote
Care was given to how the class behaves to minimise its interaction with other
packages the end-user might need for their work. The class only patches certain
commands but never redefines them.
#+end_quote

As a sidenote, ~mcidoc~ was also designed with customisation in mind by
configuring its settings through the options presented in the ~\documentclass~ and
using the macro ~\SetMCI{}~ which all its features are explained in this
documentation.

The last purpose is perhaps more in line of streamlining. While LaTeX is an
excellent typesetting language with is very powerful capabilities, it is
nevertheless a language with its quirks and customs that may not prove to be
very useful outside of its own domain and therefore the user should not be
worried of these quirks.

The user should only be responsible of the content they create. The form of the
documentation, and how the content is presented is taken care of the class
designer.

** Frequently Asked Questions

**** Where can I download the documentclass?

The documentclass is stored in the github [[https://github.com/dTmC0945/C-MCI-LaTeX-Class-mcidoc/tree/main][repo]] which you can access it in one of
two ways:

1. If you are familiar with ~git~ you can use the following command to clone it:

#+begin_src bash
git clone https://github.com/dTmC0945/C-MCI-LaTeX-Class-mcidoc.git
#+end_src

1. You can visit the website from [[https://github.com/dTmC0945/C-MCI-LaTeX-Class-mcidoc/tree/main][here]]. Once you are in the repo you need to
   click [Code] and then [Download ZIP].  Once downloaded, you need to extract
   the zip file and then place the ~mcidoc.cls~ file on the *same folder* where the
   main ~.tex~ file is.
   
**** What is SetMCI ? How do I use it?

~\SetMCI~ is a custom command designed to streamline the interaction between the
end user (i.e., you) and the typesetting software (i.e., LaTeX). To get more
information about what options this command takes and relevant examples, please
consult the [[https://dtmc0945.github.io/C-MCI-LaTeX-Class-mcidoc/][official documentation]].

**** What is LaTeX? Isn't is a type of plastic?

Well, yes but in this context, no. It is a typesetting language which is
designed to produce high quality scientific work and technical documents.

However, It seems you might need a good refreshment on important concepts on
LaTeX, which you can access from [[https://github.com/dTmC0945/L-MCI-BSc-Academic-Writing][here]].

**** I Don't know what to do with this file. What is a .cls file ?

~mcidoc.cls~ is a class file. It is a set of instruction telling how the document
should *behave*. For example, margins of the page, where should the title be, the
style of chapters, so on and so forth. Using a class file allows the author
(i.e., you) to not worry about formatting and focus more on what is important
content.

**** I want to use word (.docx) instead of LaTeX. Will you help me?

No.

**** Can I use it in Overleaf?

Technically yes. But, due to its implementation, it might cause problems in
compilation time. It is heavily suggested to have an *offline* installation such
as:

- [[https://www.tug.org/texlive/][TeX Live]] (Windows, macOS, Linux)
- [[https://miktex.org/][MiKTeX]]   (Windows)
- [[https://www.tug.org/mactex/][MacTeX]]   (macOS)

and work with a good text editor.

**** What Editor Should I Use?

Excellent question. The following are good LaTeX editors with built in support:

- [[www.texstudio.org][TeXstudio]]
- [[https://www.xm1math.net/texmaker/][Texmaker]]

Some general purpose text editors can also be used to work with LaTeX very well.

- [[https://code.visualstudio.com/][Visual Studio Code]]
- [[https://www.vim.org/][Vim]] or [[https://neovim.io/][Neovim]]
- [[https://www.gnu.org/software/emacs/][Emacs]]
- [[https://notepad-plus-plus.org/][Notepad++]]
  
**** I've found a Bug. How can I Report It?

As this is not a small project (in terms of LaTeX), there can be problems, and
edge cases where there can be problems. If you happen to find some problems,
please use the official [[https://github.com/dTmC0945/C-MCI-LaTeX-Class-mcidoc/tree/main][repo]] to report it.

** Patch Information

*** Release SS.2026.2

- Fixed zero width spacing in ~mcidoc.cls~
- Added truncated lines to header to stop overflowing  
